// src/pages/modules/AlertsPage.tsx
// Alerts module page — view and triage IoT alerts

import type { FC } from "react";

const AlertsPage: FC = () => {
    return (
        <div className="flex min-h-screen flex-col bg-background px-6 py-8">
            <header className="mb-6">
                <h1 className="text-2xl font-semibold text-foreground">Alerts</h1>
                <p className="text-sm text-muted-foreground">
                    Monitor and triage alerts generated by your IoT devices and services.
                </p>
            </header>

            <main className="flex flex-1 items-center justify-center">
                <p className="text-sm text-muted-foreground">
                    Alert list, filters, and details will be available here soon.
                </p>
            </main>
        </div>
    );
};

export default AlertsPage;

