<?php

declare(strict_types=1);

// database/seeders/NodeSeeder.php
// Seeds 24 demo nodes spread across both seeded networks for local development
// and node decommission simulation. Mix of active, new, and decommissioned
// statuses so all decommission UI states can be exercised.
//
// Run after: NetworkSeeder (needs network_id).

namespace Database\Seeders;

use App\Models\Network;
use App\Models\Node;
use Illuminate\Database\Seeder;

class NodeSeeder extends Seeder
{
    public function run(): void
    {
        $acme   = Network::where('network_address', 'A1B2C3')->firstOrFail();
        $globex = Network::where('network_address', 'D4E5F6')->firstOrFail();

        $rows = [
            // ── Acme HQ — Building A (14 nodes) ──────────────────────────────
            [
                'network_id'     => $acme->id,
                'name'           => 'Fire Ext — Lobby L1',
                'node_address'   => 'A1F1C3',
                'service_id'     => 'SVC-FE-001',
                'product_type'   => 'Fire Extinguisher Monitor',
                'building_name'  => 'Acme HQ Building A',
                'building_level' => 'Level 1',
                'sector_name'    => 'Lobby',
                'is_online'      => true,
                'last_online_at' => now()->subMinutes(3),
                'provisioned_at' => now()->subDays(60),
                'status'         => 'active',
            ],
            [
                'network_id'     => $acme->id,
                'name'           => 'Fire Ext — Server Room L1',
                'node_address'   => 'A1F2C4',
                'service_id'     => 'SVC-FE-002',
                'product_type'   => 'Fire Extinguisher Monitor',
                'building_name'  => 'Acme HQ Building A',
                'building_level' => 'Level 1',
                'sector_name'    => 'Server Room',
                'is_online'      => true,
                'last_online_at' => now()->subMinutes(8),
                'provisioned_at' => now()->subDays(60),
                'status'         => 'active',
            ],
            [
                'network_id'     => $acme->id,
                'name'           => 'Smoke Detector — East Wing L2',
                'node_address'   => 'B2E4D5',
                'service_id'     => 'SVC-SD-003',
                'product_type'   => 'Smoke Detector',
                'building_name'  => 'Acme HQ Building A',
                'building_level' => 'Level 2',
                'sector_name'    => 'East Wing',
                'is_online'      => true,
                'last_online_at' => now()->subMinutes(1),
                'provisioned_at' => now()->subDays(45),
                'status'         => 'active',
            ],
            [
                'network_id'     => $acme->id,
                'name'           => 'Smoke Detector — West Wing L2',
                'node_address'   => 'B2W5D6',
                'service_id'     => 'SVC-SD-004',
                'product_type'   => 'Smoke Detector',
                'building_name'  => 'Acme HQ Building A',
                'building_level' => 'Level 2',
                'sector_name'    => 'West Wing',
                'is_online'      => false,
                'last_online_at' => now()->subHours(3),
                'provisioned_at' => now()->subDays(45),
                'status'         => 'active',
            ],
            [
                'network_id'     => $acme->id,
                'name'           => 'Temp & Humidity — Office L3',
                'node_address'   => 'C3T6E7',
                'service_id'     => 'SVC-TH-005',
                'product_type'   => 'Temperature & Humidity Sensor',
                'building_name'  => 'Acme HQ Building A',
                'building_level' => 'Level 3',
                'sector_name'    => 'Open Office',
                'is_online'      => true,
                'last_online_at' => now()->subMinutes(15),
                'provisioned_at' => now()->subDays(30),
                'status'         => 'active',
            ],
            [
                'network_id'     => $acme->id,
                'name'           => 'Temp & Humidity — Meeting Room L3',
                'node_address'   => 'C3T7F8',
                'service_id'     => 'SVC-TH-006',
                'product_type'   => 'Temperature & Humidity Sensor',
                'building_name'  => 'Acme HQ Building A',
                'building_level' => 'Level 3',
                'sector_name'    => 'Meeting Room B',
                'is_online'      => true,
                'last_online_at' => now()->subMinutes(10),
                'provisioned_at' => now()->subDays(30),
                'status'         => 'active',
            ],
            [
                'network_id'     => $acme->id,
                'name'           => 'Gas Detector — Kitchen L1',
                'node_address'   => 'D4G8F9',
                'service_id'     => 'SVC-GD-007',
                'product_type'   => 'Gas Detector',
                'building_name'  => 'Acme HQ Building A',
                'building_level' => 'Level 1',
                'sector_name'    => 'Kitchen',
                'is_online'      => true,
                'last_online_at' => now()->subMinutes(2),
                'provisioned_at' => now()->subDays(50),
                'status'         => 'active',
            ],
            [
                'network_id'     => $acme->id,
                'name'           => 'Gas Detector — Basement',
                'node_address'   => 'D4G9A1',
                'service_id'     => 'SVC-GD-008',
                'product_type'   => 'Gas Detector',
                'building_name'  => 'Acme HQ Building A',
                'building_level' => 'Basement',
                'sector_name'    => 'Utility Room',
                'is_online'      => false,
                'last_online_at' => now()->subDays(1),
                'provisioned_at' => now()->subDays(50),
                'status'         => 'active',
            ],
            [
                'network_id'     => $acme->id,
                'name'           => 'Fire Ext — Stairwell L4',
                'node_address'   => 'A4F3B2',
                'service_id'     => 'SVC-FE-009',
                'product_type'   => 'Fire Extinguisher Monitor',
                'building_name'  => 'Acme HQ Building A',
                'building_level' => 'Level 4',
                'sector_name'    => 'Stairwell A',
                'is_online'      => false,
                'last_online_at' => now()->subHours(6),
                'provisioned_at' => now()->subDays(10),
                'status'         => 'new',
            ],
            [
                'network_id'     => $acme->id,
                'name'           => 'Smoke Detector — Rooftop',
                'node_address'   => 'E5R1A2',
                'service_id'     => 'SVC-SD-010',
                'product_type'   => 'Smoke Detector',
                'building_name'  => 'Acme HQ Building A',
                'building_level' => 'Rooftop',
                'sector_name'    => 'Plant Room',
                'is_online'      => false,
                'last_online_at' => null,
                'provisioned_at' => null,
                'status'         => 'new',
            ],
            [
                'network_id'     => $acme->id,
                'name'           => 'Temp & Humidity — Rooftop',
                'node_address'   => 'C5R2B3',
                'service_id'     => 'SVC-TH-011',
                'product_type'   => 'Temperature & Humidity Sensor',
                'building_name'  => 'Acme HQ Building A',
                'building_level' => 'Rooftop',
                'sector_name'    => 'External',
                'is_online'      => false,
                'last_online_at' => null,
                'provisioned_at' => null,
                'status'         => 'new',
            ],
            // Already decommissioned — should NOT appear in the node list
            [
                'network_id'     => $acme->id,
                'name'           => 'Fire Ext — Old Cafeteria (Decommissioned)',
                'node_address'   => 'F6D1C2',
                'service_id'     => 'SVC-FE-012',
                'product_type'   => 'Fire Extinguisher Monitor',
                'building_name'  => 'Acme HQ Building A',
                'building_level' => 'Level 1',
                'sector_name'    => 'Old Cafeteria',
                'is_online'      => false,
                'last_online_at' => now()->subDays(30),
                'provisioned_at' => now()->subDays(90),
                'status'         => 'decommissioned',
            ],
            [
                'network_id'     => $acme->id,
                'name'           => 'Gas Detector — Old Lab (Decommissioned)',
                'node_address'   => 'G7L2D3',
                'service_id'     => 'SVC-GD-013',
                'product_type'   => 'Gas Detector',
                'building_name'  => 'Acme HQ Building A',
                'building_level' => 'Level 2',
                'sector_name'    => 'Old Lab',
                'is_online'      => false,
                'last_online_at' => now()->subDays(45),
                'provisioned_at' => now()->subDays(120),
                'status'         => 'decommissioned',
            ],
            [
                'network_id'     => $acme->id,
                'name'           => 'Smoke Detector — Relocated Unit (Decommissioned)',
                'node_address'   => 'H8R3E4',
                'service_id'     => 'SVC-SD-014',
                'product_type'   => 'Smoke Detector',
                'building_name'  => 'Acme HQ Building A',
                'building_level' => 'Level 3',
                'sector_name'    => 'East Corridor',
                'is_online'      => false,
                'last_online_at' => now()->subDays(20),
                'provisioned_at' => now()->subDays(80),
                'status'         => 'decommissioned',
            ],

            // ── Globex — Main Floor (10 nodes) ───────────────────────────────
            [
                'network_id'     => $globex->id,
                'name'           => 'Smoke Detector — Entry Gate',
                'node_address'   => 'G1S1A2',
                'service_id'     => 'SVC-GX-SD-001',
                'product_type'   => 'Smoke Detector',
                'building_name'  => 'Globex Main Building',
                'building_level' => 'Ground Floor',
                'sector_name'    => 'Entry Gate',
                'is_online'      => true,
                'last_online_at' => now()->subMinutes(5),
                'provisioned_at' => now()->subDays(20),
                'status'         => 'active',
            ],
            [
                'network_id'     => $globex->id,
                'name'           => 'Gas Detector — Production Line A',
                'node_address'   => 'G2G2B3',
                'service_id'     => 'SVC-GX-GD-002',
                'product_type'   => 'Gas Detector',
                'building_name'  => 'Globex Main Building',
                'building_level' => 'Ground Floor',
                'sector_name'    => 'Production Line A',
                'is_online'      => true,
                'last_online_at' => now()->subMinutes(2),
                'provisioned_at' => now()->subDays(20),
                'status'         => 'active',
            ],
            [
                'network_id'     => $globex->id,
                'name'           => 'Gas Detector — Production Line B',
                'node_address'   => 'G3G3C4',
                'service_id'     => 'SVC-GX-GD-003',
                'product_type'   => 'Gas Detector',
                'building_name'  => 'Globex Main Building',
                'building_level' => 'Ground Floor',
                'sector_name'    => 'Production Line B',
                'is_online'      => true,
                'last_online_at' => now()->subMinutes(4),
                'provisioned_at' => now()->subDays(20),
                'status'         => 'active',
            ],
            [
                'network_id'     => $globex->id,
                'name'           => 'Door Sensor — Warehouse Exit',
                'node_address'   => 'G4D4D5',
                'service_id'     => 'SVC-GX-DS-004',
                'product_type'   => 'Door / Window Sensor',
                'building_name'  => 'Globex Main Building',
                'building_level' => 'Ground Floor',
                'sector_name'    => 'Warehouse',
                'is_online'      => true,
                'last_online_at' => now()->subMinutes(1),
                'provisioned_at' => now()->subDays(15),
                'status'         => 'active',
            ],
            [
                'network_id'     => $globex->id,
                'name'           => 'Door Sensor — Server Rack Room',
                'node_address'   => 'G5D5E6',
                'service_id'     => 'SVC-GX-DS-005',
                'product_type'   => 'Door / Window Sensor',
                'building_name'  => 'Globex Main Building',
                'building_level' => 'Level 1',
                'sector_name'    => 'Server Rack Room',
                'is_online'      => false,
                'last_online_at' => now()->subHours(4),
                'provisioned_at' => now()->subDays(15),
                'status'         => 'active',
            ],
            [
                'network_id'     => $globex->id,
                'name'           => 'Temp & Humidity — Control Room',
                'node_address'   => 'G6T6F7',
                'service_id'     => 'SVC-GX-TH-006',
                'product_type'   => 'Temperature & Humidity Sensor',
                'building_name'  => 'Globex Main Building',
                'building_level' => 'Level 1',
                'sector_name'    => 'Control Room',
                'is_online'      => true,
                'last_online_at' => now()->subMinutes(20),
                'provisioned_at' => now()->subDays(25),
                'status'         => 'active',
            ],
            [
                'network_id'     => $globex->id,
                'name'           => 'Smoke Detector — Storage Area',
                'node_address'   => 'G7S7G8',
                'service_id'     => 'SVC-GX-SD-007',
                'product_type'   => 'Smoke Detector',
                'building_name'  => 'Globex Main Building',
                'building_level' => 'Ground Floor',
                'sector_name'    => 'Storage Area',
                'is_online'      => false,
                'last_online_at' => now()->subHours(1),
                'provisioned_at' => now()->subDays(5),
                'status'         => 'new',
            ],
            [
                'network_id'     => $globex->id,
                'name'           => 'Gas Detector — Fuel Storage',
                'node_address'   => 'G8G8H9',
                'service_id'     => 'SVC-GX-GD-008',
                'product_type'   => 'Gas Detector',
                'building_name'  => 'Globex Main Building',
                'building_level' => 'Basement',
                'sector_name'    => 'Fuel Storage',
                'is_online'      => false,
                'last_online_at' => null,
                'provisioned_at' => null,
                'status'         => 'new',
            ],
            [
                'network_id'     => $globex->id,
                'name'           => 'Door Sensor — Loading Bay',
                'node_address'   => 'G9D9I1',
                'service_id'     => 'SVC-GX-DS-009',
                'product_type'   => 'Door / Window Sensor',
                'building_name'  => 'Globex Main Building',
                'building_level' => 'Ground Floor',
                'sector_name'    => 'Loading Bay',
                'is_online'      => false,
                'last_online_at' => null,
                'provisioned_at' => null,
                'status'         => 'new',
            ],
            // Already decommissioned — should NOT appear in decommission node list
            [
                'network_id'     => $globex->id,
                'name'           => 'Temp & Humidity — Decommissioned Sector',
                'node_address'   => 'G0T0J2',
                'service_id'     => 'SVC-GX-TH-010',
                'product_type'   => 'Temperature & Humidity Sensor',
                'building_name'  => 'Globex Main Building',
                'building_level' => 'Level 2',
                'sector_name'    => 'Old Assembly Area',
                'is_online'      => false,
                'last_online_at' => now()->subDays(60),
                'provisioned_at' => now()->subDays(100),
                'status'         => 'decommissioned',
            ],
        ];

        $counts = ['acme' => 0, 'globex' => 0];

        foreach ($rows as $data) {
            Node::firstOrCreate(['service_id' => $data['service_id']], $data);
            $counts[$data['network_id'] === $acme->id ? 'acme' : 'globex']++;
        }

        $this->command->newLine();
        $this->command->table(
            ['Network', 'Nodes seeded', 'Active', 'New', 'Decommissioned'],
            [
                [
                    $acme->name,
                    $counts['acme'],
                    collect($rows)->where('network_id', $acme->id)->where('status', 'active')->count(),
                    collect($rows)->where('network_id', $acme->id)->where('status', 'new')->count(),
                    collect($rows)->where('network_id', $acme->id)->where('status', 'decommissioned')->count(),
                ],
                [
                    $globex->name,
                    $counts['globex'],
                    collect($rows)->where('network_id', $globex->id)->where('status', 'active')->count(),
                    collect($rows)->where('network_id', $globex->id)->where('status', 'new')->count(),
                    collect($rows)->where('network_id', $globex->id)->where('status', 'decommissioned')->count(),
                ],
            ]
        );
    }
}
